[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.cjs"
