[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production node dist/index.cjs"
